### ISSUE TITLE
Using libcleri as a "preprocessor"

### ISSUE THREAD

**Issue by IngwiePhoenix** [transceptor-technology/libcleri#15]
Hello!

I would like to know if the following would be possible: In a project of mine, I'd like to extend the syntax of a used scripting language. Since I can not directly manipulate the parser of that language, I'd like to implement a preprocessor ontop of it. Can I use this library for this?

For simplicity, let's say I am using a JavaScript-like language and would like to add namespacing with a syntax like this:

```
namespace foo {
  function bar() {}
}
```

I would like to pick up the keyword `namespace`, the identifier `foo`, and the contents of the curly braces. Then, I'd like to re-shape that code into this:

```
__namespace("foo", function() {
  function bar() {
  }
});
```

Would this be possible?

Thank you in advance!

**Comment by joente** [comment]
Probably you can, the difficult part is making your grammar to understand "enough" of JavaScript so it can correctly skip the code between the `{..}`. For example correctly handle `{` in strings, comments etc. Once this is done it should be fairly easy to read the code and output the code again using some other format.
