### ISSUE TITLE
CMakeLists support

### ISSUE THREAD

**Issue by undisputed-seraphim** [transceptor-technology/libcleri#7]
I've been following this project with some interest.
Is there any interest for CMake support? I have prepared a CMakeLists file in my fork.
I intend to try to create a CMakeLists file for all siridb source code if there is interest for it.

**Comment by joente** [comment]
Thanks! Adding CMake support would be useful so eventually we could move from bare makefiles to cmake. (at the moment debian packaging is build upon the current makefiles)
